---
title: 'Analysis of longitudinal data'
description: 'Repeated measure data'
---

## Meet and Repeat

```yaml
type: NormalExercise
key: f9ad1f5b4a
lang: r
xp: 100
skills: 1
```

Welcome to the *Analysis of longitudinal data* chapter.

Chapter details

`@instructions`
- Read the `BPRS` data into memory
- Print out the (column) names of the data
- Look at the structure of the data
- Print out summaries of the variables in the data

`@hint`
- Use `str()` to see structure
- Use `summary()` to compute summaries

`@pre_exercise_code`
```{r}

```

`@sample_code`
```{r}
# read the human (adding BPRS soon) data
bprs <- read.table("http://s3.amazonaws.com/assets.datacamp.com/production/course_2218/datasets/human1.txt", sep  =",", header = T)

# look at the (column) names of human
names(bprs)

# look at the structure of human


# print out summaries of the variables


```

`@solution`
```{r}
# read the human data
bprs <- read.table("http://s3.amazonaws.com/assets.datacamp.com/production/course_2218/datasets/human1.txt", sep  =",", header = T)

# look at the (column) names of human
names(bprs)

# look at the structure of human
str(bprs)

# print out summaries of the variables
summary(bprs)
```

`@sct`
```{r}

test_function("str", args = "object",incorrect_msg = "Please look at the structure of the BPRS data frame")
test_function("summary", args = "object",incorrect_msg = "Please print out summaries of the variables in the BPRS data frame")

test_error()
success_msg("Awsome, you have mastered an important first step of data analysis!")
```
