# Data wrangling

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE)
```


## 1 loading more datasets

```{r}

## meta: 
##browseURL("https://archive.ics.uci.edu/ml/datasets/STUDENT+ALCOHOL+CONSUMPTION")

## read the math class questionaire data
math <- read.table("../datasets/student-mat.csv",sep=";",header=TRUE)

## look at the column names
colnames(math)

## read the portuguese class questionaire data
por <- read.table("../datasets/student-por.csv",sep=";",header=TRUE)

## look at the column names
colnames(por)

```
## 2 joining two datasets
```{r}

## common columns to merge the datasets by
join_by <- c("school","sex","age","address","famsize","Pstatus","Medu","Fedu","Mjob","Fjob","reason","nursery","internet")

## access the dplyr library
library(dplyr)

## join the two datasets by selected common variables
math_por <- inner_join(math, por, by = join_by, suffix = c(".math", ".por"))

## see the new column names
colnames(math_por)
```

## 3 glimpse at the joined dataset

```{r}

## access the dplyr library
library(dplyr)

## glimpse at the new data
glimpse(math_por) 

```
## 4 Transforming by looping

```{r}


join_by <- c("school","sex","age","address","famsize","Pstatus","Medu","Fedu","Mjob","Fjob","reason","nursery","internet")

## which columns in the datasets were not used for joining the data
notjoined_columns <- colnames(math)[!colnames(math) %in% join_by]

## create a new data frame with the common columns
alc <- select(math_por, one_of(join_by))

## access the dplyr library
library(dplyr)

## average/combine the rest of the columns
for(column_name in notjoined_columns) {
  
  df <- select(math_por, starts_with(column_name))
  
  if(is.numeric(select(df, 1))) {
    alc[column_name] <- rowMeans(df)
  } else {
    alc[column_name] <- select(df, 1)
  }
}

# final column names of the data
colnames(alc)
```

## 5 Mutating and exploring
```{r}

library(dplyr)
library(ggplot2)

## combine weekday and weekend alcohol use into alc_use
alc <- mutate(alc, alc_use = (Dalc + Walc) / 2)

## draw a histogram of alcohol use
qplot(alc_use, data = alc, bins = 10, main = "Student alcohol consumption")

## draw a histogram of student grades
qplot(G3, data = alc, bins = 10, main = "Student final grades")



```

## 6 Binarizing a variable
```{r}
## transform alc_use into a binary (T, F) variable high_use
alc$high_use <- alc$alc_use > 2

## draw a bar plot
qplot(high_use, data = alc)

# save the data
# write.table(file = "../datasets/alc.txt", alc, sep = ",", row.names = F)
```

## 7 exploring relationships with cross tables
```{r}


library(descr)

crosstab(alc$sex, alc$high_use, prop.c = T, prop.r = T)

crosstab(alc$age, alc$high_use, prop.c = T, prop.r = T)

```
## Analysis: Logistic regression

## 8 fitting a logistic regression model

```{r}


m1 <- glm(high_use ~ sex + age + G3, data = alc, family = binomial)

summary(m1)


```